owner: magnatome
repo: epic-vs-ikon-status-page
sites:
  - name: Epic vs Ikon
    url: https://www.epicorikon.com
  - name: Resort Map
    url: https://www.epicorikon.com/map
  - name: Compare Passes
    url: https://www.epicorikon.com/passes/compare
status-website:
  cname: status.epicorikon.com
  logoUrl: https://raw.githubusercontent.com/magnatome/epic-vs-ikon-status-page/master/assets/favicon.png
  favicon: https://raw.githubusercontent.com/magnatome/epic-vs-ikon-status-page/master/assets/favicon.png
  name: Epic vs Ikon Status
  theme: light
  metaTags:
    - name: 'robots'
      content: 'noindex'
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.epicorikon.com
    - title: Resorts Map
      href: https://www.epicorikon.com/map
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
workflowSchedule:
  uptime: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *" # Check every 5 minutes
  responseTime: "51 */1 * * *" # Check response time every hour
  graphs: "55 */3 * * *" # Generate graphs every 3 hours
  staticSite: "58 */3 * * *"  # Generate static site every 3 hours
  summary: "59 23 * * *" # Generate summary at the end of each day
  updateTemplate: "0 0 * * 2" # Update the template every Tuesday
  updates: "0 0 1,15 * *" # Check for package updates twice a month
