owner: magnatome
repo: epic-vs-ikon-status-page
sites:
  - name: Epic vs Ikon
    url: https://www.epicorikon.com
  - name: Resort Map
    url: https://www.epicorikon.com/map
  - name: Compare Passes
    url: https://www.epicorikon.com/passes/compare
status-website:
  cname: status.epicorikon.com
  logoUrl: https://raw.githubusercontent.com/magnatome/epic-vs-ikon-status-page/master/assets/favicon.png
  favicon: https://raw.githubusercontent.com/magnatome/epic-vs-ikon-status-page/master/assets/favicon.png
  name: Epic vs Ikon Status
  theme: light
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.epicorikon.com
    - title: Resorts Map
      href: https://www.epicorikon.com/map
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
workflowSchedule:
  # Check status every 10 minutes, except 50 past because response time also checks uptime
  uptime: "0,10,20,30,40 * * * *"
  # Check response time every hour
  responseTime: "50 * * * *"
  # Generate graphs every 3 hours
  graphs: "55 */3 * * *"
  # Generate summary at the end of each day (MT)
  summary: "5 8 * * *"
  # Re-generate static site code every Tuesday
  staticSite: "5 8 * * 2"
  # Update the template every Wednesday
  updateTemplate: "5 8 * * 3"
  # Check for package updates twice a month
  updates: "1 0 1,15 * *"
