owner: magnatome
repo: epic-vs-ikon-status-page
sites:
  - name: Epic vs Ikon
    url: https://www.epicorikon.com
  - name: Resort Map
    url: https://www.epicorikon.com/map
  - name: Compare Passes
    url: https://www.epicorikon.com/passes/compare
status-website:
  cname: status.epicorikon.com
  logoUrl: https://raw.githubusercontent.com/magnatome/epic-vs-ikon-status-page/master/assets/favicon.png
  favicon: https://raw.githubusercontent.com/magnatome/epic-vs-ikon-status-page/master/assets/favicon.png
  name: Epic vs Ikon Status
  theme: light
  metaTags:
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.epicorikon.com
    - title: Resorts Map
      href: https://www.epicorikon.com/map
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
workflowSchedule:
  # Check every 6 minutes, except 54 because response time also checks uptime
  uptime: "0,6,12,18,24,30,36,42,48 * * * *"
  # Check response time every hour
  responseTime: "54 */1 * * *"
  # Generate graphs every 3 hours
  graphs: "55 */3 * * *"
  # Generate static site every 3 hours
  staticSite: "58 */3 * * *"
  # Generate summary at the end of each day
  summary: "59 23 * * *"
  # Update the template every Tuesday
  updateTemplate: "0 0 * * 2"
  # Check for package updates twice a month
  updates: "0 0 1,15 * *"
