owner: magnatome
repo: epic-vs-ikon-status-page
sites:
  - name: Epic vs Ikon
    url: https://www.epicorikon.com
  - name: Resort Map
    url: https://www.epicorikon.com/map
status-website:
  cname: status.epicorikon.com
  logoUrl: https://raw.githubusercontent.com/magnatome/epic-vs-ikon-status-page/master/assets/favicon.png
  favicon: https://raw.githubusercontent.com/magnatome/epic-vs-ikon-status-page/master/assets/favicon.png
  name: Epic vs Ikon Status
  theme: light
  metaTags:
    - name: 'robots'
      content: 'noindex'
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.epicorikon.com
    - title: Resorts Map
      href: https://www.epicorikon.com/map
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
